### ISSUE TITLE
Sending commands without serial monitor

### ISSUE THREAD

**Issue by kitmir** [sepp89117/GoPro-Multiple-Smart-Remote-ESP8266#1]
Hello,

Thanks for the great work. I tested this on my GoPro Hero5 and it works very well.
I must say I tested an older version of it and it still works. I got some errors with TimedAction.h and did not have time to look into it. So I used the old version.

I have one question/issue though...

Is it in anyway possible to use this for a time-lapse?
I would like to send commands:
- turn camera on
- connect
- take a picture
- disconnect
- let camera sleep for another 15 minutes :)

I have fiddled around with your code a bit but could not succeed. the best case I could take only one picture or some pictures with random intervals.

Would really appreciate if you could guide me a bit...

I have a utopia to make a time-lapse of the nature for a year from my house.

Thanks in advance!

**Comment by sepp89117** [comment]
Hi,

I'm so sorry that I answer so late!

I am not sure if that is possible. But I think so.
The cameras go into the stand-by and continue to search for a connection. After some time, they go out completely. I do not know how long they are in standby, so I do not know how long the interval can be.

Basically, the procedure is therefore:
- turn on camera by hand
- Set photo mode as default mode by hand
- Start the program
- Program takes a picture
- Program turns off the camera
- Program waits 15 minutes
- and again

The program is relatively simple, I think. Unfortunately, I currently have little time to deal with it.

In any case do not work with `millis ()`. They overflow after about 50 days and start at zero.

Please tell me if you still need help. I will find time to write a code for you. Is actually an interesting idea.

Achso, I think only the battery of the camera will not last forever ...

**Comment by sepp89117** [comment]
The problem with TimedAction exists from Arduino version 1.6.x. To fix it you need a new library.
Glumgad offers version 2.0 of TimedAction. It works like that. https://github.com/Glumgad/TimedAction
The lib is needed at least to send the heartbeat.

**Comment by chung1608** [comment]
> The problem with TimedAction exists from Arduino version 1.6.x. To fix it you need a new library.
> Glumgad offers version 2.0 of TimedAction. It works like that. https://github.com/Glumgad/TimedAction
> The lib is needed at least to send the heartbeat.

I just know a little bit about arduino code so can you optimize code only for control 1 cam, plz

**Comment by sepp89117** [comment]
@chung1608 Hi, the code works the same with one camera as it does with 8 cameras.
With Cam1Mac you only have to enter the MAC of your cam in the curly brackets.
uint8_t Cam1Mac [6] = {0x04, 0x41, 0x69, 0x4F, 0x0F, 0x4B};
Check aut the new Version of my Code

**Comment by chung1608** [comment]
> @chung1608 Hi, the code works the same with one camera as it does with 8 cameras.
> With Cam1Mac you only have to enter the MAC of your cam in the curly brackets.
> uint8_t Cam1Mac [6] = {0x04, 0x41, 0x69, 0x4F, 0x0F, 0x4B};
> Check aut the new Version of my Code

Thank you, more question:
1. Can you share full cam command 
2. How to get cam status and setting

**Comment by sepp89117** [comment]
Re 1. I don't know what you mean. The commands for the serial monitor can be found in the readme
Re 2. The status of each cam is displayed every few seconds. The settings cannot be called up or changed with the smart remote.

**Comment by chung1608** [comment]
> Re 1. I don't know what you mean. The commands for the serial monitor can be found in the readme
> Re 2. The status of each cam is displayed every few seconds. The settings cannot be called up or changed with the smart remote.

Thank you I have find mean of the command send to gopro in web https://hobbyrobo.com/gopro-url-commands/
You have know command which can be change video preset
