### ISSUE TITLE
No luck with Gopro Hero8

### ISSUE THREAD

**Issue by Bert1000** [sepp89117/GoPro-Multiple-Smart-Remote-ESP8266#2]
Great initiative! I tested it on my GoPro Hero8 but it does not work. I am using a WeMos D1 mini. I tried "connect device" "Remote" on the GoPro (it responds with "Put Remote in pairing mode"). Meanwhile I was sending rc1 commands but no response. 
I also had issues using the GoPro App, but those were resolved with the latest firmware (2.50) that came out Yesterday. GoPro states that the new firmware would improve stability with "The Remote". A new remote will come out soon because so far there is no remote for the latest version (Hero9). 
I also figured out that after some time the GoPro goes into a deep sleep state and cannot be woken up any more using the GoPro App (after approximately 1 hour?). Something to consider when using remote controllers.
Looking forward to your updates, I will gladly test them!

**Comment by sepp89117** [comment]
Hello, please check first which MAC address your Wemos module has. You only have to send rc1 once. The remote is now active. You should then be able to connect the cam without any problems if the setup of your module is correct. So please check the MAC address of the access point after the rc1 command.

**Comment by Bert1000** [comment]
I assume you mean the MAC address of my Hero8? I did copy it into the corresponding line (Cam1Mac[6]=...). I don't think I should do anything with the Wemos MAC address?

**Comment by sepp89117** [comment]
Hello, the MAC address of your Wemos module needs to be adjusted. The corresponding lines are in the code. You don't really have to do anything. Unfortunately I don't know whether it works with the Wemos as it does with the ESP8266.
I've optimized the code for use with the serial moitor. The commands are simpler. Please check readme and test the new code. With the "on" command, the RC is started and the MAC of your module is also displayed. Which MAC is shown?

**Comment by sepp89117** [comment]
The result should look like this:
11:30:39.380 -> Ready!
11:46:06.265 -> RC startetd
11:46:06.265 -> RC IP address: 10.71.79.1
11:46:06.265 -> RC MAC address: 86:f3:eb:e4:23:dd
11:46:12.641 -> Cam 1 connected to AP
11:46:14.643 -> Cam 1 has sent: 
11:46:14.643 -> Mode: video mode
11:46:14.643 -> State: standby
11:46:14.643 -> 
11:46:17.661 -> Cam 1 has sent: 
11:46:17.661 -> Mode: video mode
11:46:17.661 -> State: standby
11:46:17.661 ->

**Comment by sepp89117** [comment]
Unfortunately I only have Hero5 cameras and an ESP8266 and an ESP32 module. I can neither test it with Wemos nor with Hero8.

**Comment by Bert1000** [comment]
Thanks, I can confirm now that the previous code and this code works now with Hero8. I only had to "reset connections" in my Hero8 and do a new "connect device" "Remote".
After opening serial port and sending <rc1> the Wemos responds with:
12:38:26.732 -> RC startetd
12:38:26.732 -> RC IP address: 10.71.79.1
12:38:26.732 -> RC MAC address: 84:f3:eb:e4:23:dd
(not the other things you mentioned)

You may need to check the README.md, the commands are lacking:
rc1  //start remote
rc0  //stop remote
sh1 //shutter start
sh0  //shutter stop
cmv  //change mode to video
cmp  //change mode to photo
cmb //change mode to burst
cml  //change mode to timelapse
pw0  //power off

To conclude, your script is nearly perfect and works for a Wemos D1 mini (<2 euro at AliExp). Unfortunately there is no pw1 option (power on). This is crucial for me because I cannot leave the camera powered on since this would drain the batteries. My application is taking short recordings during a kayak trip. I have the camera mounted out of reach and such a trip lasts a few hours. It seems possible to wake up the Hero's with a special WiFi wake up command (I remember reading about it somewhere). Would be great if you can implement this!

**Comment by sepp89117** [comment]
Nice!
I changed the commands on purpose. This should serve a simple operation by means of a serial monitor. The commands with the "<>" brackets are suitable for my PC application "GoEasyPro".

I have implemented a Wake on Lan function. Can you test it? Send "wakeup" via serial monitor.

**Comment by Bert1000** [comment]
I am impressed, it works perfectly fine, thanks a lot! It already wakes up the Hero8 when sending "on" through serial monitor for the first time. After "power0" command  I need to use the "wakeup" command and it takes about 8 seconds for the Hero8 to start waking up. So you may consider a longer delay because the serial monitor reports after 3 s "Cams connected: 0".
I will now investigate how to use it as a remote control with some switches.

**Comment by sepp89117** [comment]
Hello, when the camera turns on with the "on" command, they were only in standby. The cameras do not wake up from deep sleep when you switch on the remote. Then the "wakeup" should be used.
The wakeup command switches the remote off before the WoL signal and on again after 3 seconds. After switching on, the info is always displayed. Of course, 0 cameras are then connected.
I do it this way because I was hoping that by switching on the remote, the cameras might go into operating mode after WoL.
So your test was not entirely correct and does not make any statement that WoL works. It doesn't seem to work with my Hero5.

**Comment by Bert1000** [comment]
Well, it is a bit more complicated with the Hero8. The camera needs to be turned on manually first (after a battery replacement or after some hours of inactivity). It cannot be turned on with "wakeup" then. After manually switching the Hero8 on it subsequently can be turned off with "power0", so it needs to do some communication with the remote. After that, the Hero8 seems really off, but I think it is in a deep sleep. Next it can be controlled with your remote script: "on" makes the remote AND Hero switch on. If I leave the remote on, a "wakeup" command switches the Hero8 on again. But, in practice, to save remote control battery, I would turn off remote also.
My observation is that this deep sleep state (no display, no red light) lasts about 2 hours, so it means that as long as I use the remote at least once every 2 hours it is fine, no need to switch it on manually. I also observe this when using the GoPro App, after some time it cannot find the Hero8 any more and I need to start it manually first. 
Maybe the new GoPro "The Remote" will be able to do a wake up after changing Hero8 batteries (or after >2 hours rest),  but it hasn't been tested yet (too new). What I know is that it uses Bluetooth.

**Comment by sepp89117** [comment]
The same procedure applies to Hero5. However, wakeup cannot work because there is no WiFi connected. Wakeup is not functional! As you have correctly recognized, the cameras wake up with the remote when the cameras are not in deep sleep. After the power0 command, the cameras go off, but they watch for a while whether the remote goes back on (look for the remote's access point). That means you can switch off the remote completely. The cameras wake up again with the remote if they are not already completely off.
In the next release, wake on lan will no longer exist because it is useless.
If the app can no longer find the cameras, a restart using the remote also helps. Send power0, off, on. The cameras go off and on again and the app can find them again.
What is your plan to use the code? With a display and a battery? I was already thinking of combining it with a touchscreen and a battery in one housing.

**Comment by Bert1000** [comment]
"Wakeup" is still useful if I leave the Wemos on, otherwise I would need to send "off" and then "on" again. I was thinking of a minimalist design, with one power switch such that powering on also activates the Hero8. Then a push button to start recording and also to stop recording (pressing same button again while recording). An LED on the remote could be nice to indicate if it is really recording. Everything in a waterproof little box, perhaps with a small solar panel on top. The Wemos is very small, could be nice to design a 3d printed housing. 
A touchscreen is nice but it doesn't like water and I will mainly use it on my kayak.

**Comment by sepp89117** [comment]
I've changed "wakeup" to a more sensible procedure.

I think it is harder to build waterproof switches than a touchscreen. The tocuh screen displays are pressure-sensitive and therefore not sensitive to water. A display could provide an overview of all cameras.
But of course this is your project! Good luck, enjoy :)
