### ISSUE TITLE
Unable to record while HDMI out connected

### ISSUE THREAD

**Issue by tommy-b-10** [sepp89117/GoPro-Multiple-Smart-Remote-ESP8266#3]
Hi, 

I have a Hero 7 which I wish to control while connected to HDMI out.
Without HDMI connected this library works perfectly. However as soon as I connect the HDMI, the shutter commands do not work. Status and mode commands work fine, it is just the shutter.

Wonder if there is a different command required for shutter during hdmi live output? I don't have a smart remote myself to determine if its even possible with the smart remote either.

Thanks!

**Comment by sepp89117** [comment]
Hello, please try another parameter for the SH1 command.  That means, change the last value (0x02) to 0x01 in variable SH1.  Does it work with that?  Another possibility would be to change the command from SH to SA.  To do this, change 0x53 0x48 to 0x53 0x41 in variable SH1.  A few parameters could also be tested with SA.

**Comment by tommy-b-10** [comment]
Thanks for your quick reply sepp!

SA with 0x03 argument works to start and stop recording video! However still no luck with photos. Still trying different combinations of the SH and SA commands...

**Comment by sepp89117** [comment]
There is another command for Highlight Tag. PA with the two arguments 2 and 3.
Maybe you can try PA with just one argument.
If you use two arguments, the command will be longer. Then you have to go to "sendToCam (SH1, 14);" and also change the length (here 14).
I don't know if you know, but you can replace the hex values in the variable "SH1" with char. Means: {'S', 'H'} results in the same as {0x53, 0x48}. That might make it easier to test.

**Comment by tommy-b-10** [comment]
PA is just triggering mode changes, no photos taken?
I have SA with 0x01 taking a photo when HDMI not plugged in, but still no luck while plugged in.
Any other suggestions?

**Comment by sepp89117** [comment]
I'm sorry, but I only have one Hero 8 here right now. Unfortunately it has no HDMI connection. Therefore I cannot start any attempts.

Can you take a picture with the shutter release button on the camera when HDMI is connected? That would be a prerequisite.
There are also a number of YY commands. https://orangkucing.github.io/Hero4_I2C_Commands.html

Please try {'Y', 'Y', 0x00, 0x03, 0x17, 0x00, 0x00}

**Comment by tommy-b-10** [comment]
No worries, thank you for your help so far! 
Yes shutter button works fine with HDMI connected, and {'Y', 'Y', 0x00, 0x03, 0x17, 0x00, 0x00} worked! It did continue taking multiple photos so I have to send {'Y', 'Y', 0x00, 0x03, 0x18, 0x00, 0x00} immediately after to stop, but it works.
Appreciate your help

**Comment by sepp89117** [comment]
Nice
You are welcome
