### ISSUE TITLE
Can I use it to control more than 8 cameras?

### ISSUE THREAD

**Issue by hellolwt** [sepp89117/GoPro-Multiple-Smart-Remote-ESP8266#4]

**Comment by sepp89117** [comment]
Hi, how many cameras should be controlled?

**Comment by hellolwt** [comment]
> 
Is 10 cameras ok? I use Gopro Hero10

**Comment by sepp89117** [comment]
@hellolwt 
ESP8266 Soft AP can be connected to a maximum of 8 stations. That's what it says in the docs. Therefore, more than 8 cameras are probably not possible.

Sorry

**Comment by hellolwt** [comment]
ok. Thank you for your help!
